name: Build, test and deliver container

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest        
    
    name: test & deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: development
    
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
