name: zapfull-security-scan
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: "https://evqihf6qrp.eu-west-1.awsapprunner.com/"
