name: zapfull-security-scan
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: "https://lourdauxbob.sinners.be/"
